# Generated by Django 2.1.2 on 2018-11-10 23:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eleve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idul', models.CharField(max_length=7)),
                ('clee', models.IntegerField()),
                ('secretPartage', models.IntegerField()),
                ('dateCo', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de connection')),
                ('suspect', models.IntegerField()),
                ('photo', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name': 'eleve',
                'ordering': ['idul'],
            },
        ),
    ]
