# Generated by Django 2.1.2 on 2018-11-11 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ApiExamAI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Surveillance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suspect', models.IntegerField(default=0)),
                ('photo', models.ImageField(default=None, upload_to='')),
            ],
            options={
                'verbose_name': 'eleve',
                'ordering': ['suspect'],
            },
        ),
        migrations.RemoveField(
            model_name='eleve',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='eleve',
            name='secretPartage',
        ),
        migrations.RemoveField(
            model_name='eleve',
            name='suspect',
        ),
        migrations.AlterField(
            model_name='eleve',
            name='dateCo',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de connection'),
        ),
        migrations.AddField(
            model_name='eleve',
            name='surveille',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='ApiExamAI.Surveillance'),
        ),
    ]
