# Generated by Django 2.1.5 on 2019-01-22 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiExamAI', '0002_auto_20190122_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleve',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='static/images/eleves/'),
        ),
    ]
