# Generated by Django 2.1.2 on 2018-11-12 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ApiExamAI', '0002_auto_20181111_1420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eleve',
            name='surveille',
        ),
    ]
