# Generated by Django 2.1.5 on 2019-03-18 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiExamAI', '0004_auto_20190122_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='eleve',
            name='soundSurveillance',
            field=models.FileField(blank=True, default=None, null=True, upload_to='static/sound/surveillance/<django.db.models.fields.CharField>'),
        ),
        migrations.AddField(
            model_name='eleve',
            name='videoSurveillance',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='static/images/surveillance/<django.db.models.fields.CharField>'),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='static/images/eleves/<django.db.models.fields.CharField>'),
        ),
    ]
