# Generated by Django 2.1.5 on 2019-03-18 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiExamAI', '0005_auto_20190318_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleve',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='media/images/eleves/<django.db.models.fields.CharField>'),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='soundSurveillance',
            field=models.FileField(blank=True, default=None, null=True, upload_to='media/sound/surveillance/<django.db.models.fields.CharField>'),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='videoSurveillance',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='media/images/surveillance/<django.db.models.fields.CharField>'),
        ),
    ]
